### PR TITLE
[jjo] use statik for embedded manifests

### PR DESCRIPTION
**Pull request by jjo**
* move embedded manifests to `static/`
* adapt Makefile to make `binary` depend on `generated/statik/statik.go`
* update vendor deps

### CODE REVIEW

**Comment by jjo** [comment]
fwiw mind this being my 1st non-helloworld golang code ;)

**Comment by arapulido** [comment]
@jjo Can you rebase and resolve conflicts, please?

**Comment by ngtuna** [comment]
Thanks @jjo . This looks good to me. Overall I like this idea to embed static manifest into code. Yes we should skip `generated/statik` as somehow it will confuses folks. The minor "back side" of this PR which we could do better is requiring folks to do three steps to build the tool. We should put these steps into make file and just do `make build`. When you have time to rebase, I am happy to merge the PR and update the Makefile and travis for that.

**Comment by jjo** [comment]
Branch updated:
- rebased + resolved small conflicts
- adapted `Makefile` to re-generate embedded content before build
- removed `generated/` from committed code

**Comment by ngtuna** [comment]
Thanks @jjo I just added a commit to remove test files and _nested vendor_ and _Godeps/_ directories so the /vendor folder looks a bit smaller

**Pull request merged**
